"""
Signal dataclasses for strategy → risk → execution pipeline.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Optional


class SignalAction(str, Enum):
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


class SignalStrength(str, Enum):
    STRONG = "STRONG"
    MODERATE = "MODERATE"
    WEAK = "WEAK"


class TradingMode(str, Enum):
    INTRADAY = "intraday"
    SWING = "swing"


class Product(str, Enum):
    MIS = "MIS"   # Intraday margin (auto squared off 3:20pm)
    CNC = "CNC"   # Cash and carry (delivery/overnight)
    NRML = "NRML" # F&O normal margin


@dataclass
class Signal:
    """Entry signal generated by a strategy."""
    symbol: str
    action: SignalAction
    strategy: str
    mode: TradingMode
    product: Product

    # Price targets
    entry_price: float = 0.0          # 0 = market order
    stop_loss: float = 0.0
    target: float = 0.0

    # Sizing
    position_size_pct: float = 0.02   # % of capital (default 2%)
    sentiment_score: Optional[float] = None

    # Metadata
    strength: SignalStrength = SignalStrength.MODERATE
    confidence: float = 0.5           # 0–1
    reasoning: str = ""
    indicators: dict = field(default_factory=dict)
    generated_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    def to_dict(self) -> dict:
        return {
            "symbol": self.symbol,
            "action": self.action.value,
            "strategy": self.strategy,
            "mode": self.mode.value,
            "product": self.product.value,
            "entry_price": self.entry_price,
            "stop_loss": self.stop_loss,
            "target": self.target,
            "position_size_pct": self.position_size_pct,
            "strength": self.strength.value,
            "confidence": self.confidence,
            "reasoning": self.reasoning,
            "generated_at": self.generated_at.isoformat(),
        }


@dataclass
class ExitSignal:
    """Exit signal for an open position."""
    symbol: str
    action: SignalAction   # Always SELL for long exits
    strategy: str
    mode: TradingMode
    product: Product
    reason: str             # "stop_loss" | "target" | "trailing_stop" | "eod_close" | "kill_switch"
    exit_price: float = 0.0
    generated_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    def to_dict(self) -> dict:
        return {
            "symbol": self.symbol,
            "action": self.action.value,
            "strategy": self.strategy,
            "mode": self.mode.value,
            "product": self.product.value,
            "reason": self.reason,
            "exit_price": self.exit_price,
            "generated_at": self.generated_at.isoformat(),
        }


@dataclass
class ApprovedSignal:
    """Signal approved by risk manager, ready for execution."""
    signal: Signal
    approved_qty: int
    approved_capital: float
    risk_note: str = ""
    approved_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
